name: Deploy Next.js App

on:
  push:
    branches:
      - main # This tells GitHub to run this script only when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            git config --global --add safe.directory /home/paolo/portfolio
            cd /home/paolo/portfolio
            git fetch origin
            git reset --hard origin/main
            git clean -f -d
            npm ci
            NODE_OPTIONS="--max-old-space-size=2048" npm run build
            pm2 reload paolo-org || pm2 start npm --name "paolo-org" -- run start